server:
  port: 9998
spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.232.114:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    #url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    #password: 496179067@qq.com
    username: root
    password: Zxj12345

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.gsein.blog.front.model
  config-location: classpath:mybatis-config.xml
logging:
  level: debug
